export const tabsHeadings = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];
export const alphabetA = [
  "A1 PROS CO LTD",
  "Aavid",
  "AB CONNECTORS LTD",
  "AB Elektronic",
  "ABB Embedded Power",
  "ABLIC U.S.A. Inc.",
  "ABOV Semicon",
  "Abracon LLC.",
  "Acconeer AB",
  "ACL Staticide, Inc.",
  "Acme Electric",
  "Actel",
  "Active-Semi",
  "ACX",
  "AD Semicon",
  "Adafruit",
  "Adam Tech",
  "Adapteva, Inc.",
  "ADDtek Corp",
  "Adels-Contact",
  "Adesto Technologies",
  "Adeunis",
  "ADLINK Technology",
  "Adpower",
  "ADVANCED ANALOGIC TECHNOLOGIES INC",
  "Advanced Cable Ties",
  "Advanced Energy",
  "Advanced Interconnections",
  "Advanced Linear Devices, Inc.",
  "ADVANCED MICRO DEVICES INC",
  "Advanced Monolithic Systems",
  "Advanced Photonix",
  "Advanced Power Electronics",
  "ADVANCED POWER TECHNOLOGY INC",
  "Advanced Thermal Solutions, Inc.",
  "Advantech",
  "AEL Crystals",
  "AEM",
  "Aeris",
  "Aeroflex",
  "Agere",
  "AGILENT TECHNOLOGIES INC",
  "AIC(Analog Integrations)",
  "aigo",
  "Aim Dynamics",
  "AIM Electronics",
  "Aimtec",
  "AIPULNION(Guangzhou Aipu Elec Tech)",
  "AISHI(Aihua Group)",
  "Ai-Thinker",
  "Aker Technology",
  "AKM Semiconductor, Inc.",
  "AK-NORD GmbH",
  "Akros Silicon",
  "All Flex, Inc.",
  "Allegro MicroSystems",
  "Allen Bradley",
  "Alliance Memory, Inc.",
  "ALLIANCE SEMICONDUCTOR CORP",
  "Alliance Sensors Group",
  "Allied Components",
  "Allied Vision",
  "ALLPOWER(ShenZhen Quan Li Semiconductor)",
  "Allystar",
  "Alorium Technology",
  "Alpha and Omega Semiconductor, Inc.",
  "ALPHA SEMICONDUCTOR",
  "Alpha Wire",
  "ALPS ALPINE CO., LTD",
  "ALPS Electric",
  "Altech Corporation",
  "Altera",
  "Altium",
  "Altran Magnetics, Inc.",
  "AMAZING",
  "Amber Wireless",
  "Ambiq Micro, Inc.",
  "AMCC",
  "AMD",
  "AME",
  "American Bright",
  "American Electrical, Inc.",
  "American Microsemiconductor, Inc.",
  "American Power Conversion",
  "American Technical Ceramics",
  "American Zettler",
  "Ametek / NCC",
  "Ametherm",
  "Amgis",
  "AMI SEMICONDUCTOR",
  "AMICCOM Elec",
  "AMPCOM",
  "Amphenol",
  "Amphenol Advanced Sensors",
  "Amphenol Aerospace Operations",
  "Amphenol Anytek",
  "AMPHENOL CORP",
  "AMPHENOL FCI ASIA PTE LTD",
  "Amphenol Industrial",
  "Amphenol Information Communication & Commercial",
  "Amphenol LTW",
  "Amphenol NEXUS Technologies",
  "Amphenol Pcd",
  "Amphenol RF",
  "Amphenol SGX Sensortech",
  "Amphenol Sine Systems",
  "Amphenol Spectra-Strip",
  "Amphenol SV Microwave",
  "Amphenol Tuchel",
  "Amphenol Wilcoxon Sensing Technologies",
  "Ampleon",
  "AMPLEON NETHERLANDS B V",
  "Ampohm Wound Products",
  "Amprobe",
  "ams",
  "Amulet Technologies, LLC.",
  "Anadigics",
  "Analog Devices, Inc.",
  "Analog Integrations",
  "AnalogicTech",
  "Anaren",
  "AnaSem",
  "AnBon",
  "AnDAPT, Inc.",
  "Anderson Power Products",
  "Android Things",
  "Antenova",
  "ANUKI",
  "Aosong (Guangzhou) Elec",
  "Apacer",
  "APAQ Tech",
  "APEM Inc.",
  "APEX",
  "Apex Microtechnology",
  "Apex Tool Group",
  "API Delevan",
  "API Technologies Corp.",
  "APM Hexseal",
  "APPLIED MICRO CIRCUITS CORP",
  "Applied Power",
  "Aptina",
  "APTIV(Delphi)",
  "Aquantia Corp",
  "Arbor",
  "Arcol",
  "Arduino",
  "ARGOSY(Argosy Research Inc.)",
  "Aries Electronics, Inc.",
  "ARISTO-CRAFT/ L M P INC",
  "ARKLED(Wuxi ARK Tech Elec)",
  "ARM",
  "Arndt Electronic",
  "AROMAT CORP",
  "Array Connector Corporation",
  "Artaflex Inc.",
  "ARTERY",
  "Artesyn Embedded Power",
  "Asahi Kasei",
  "Ascend",
  "ASI SEMICONDUCTOR INC",
  "ASSMANN WSW Components",
  "Astro Tool Corp.",
  "ASTRODYNE TDI CORP",
  "Astrolab",
  "ATC",
  "Atmel (Microchip Technology)",
  "Atop Technologies",
  "ATP Electronics, Inc.",
  "Audiowell",
  "Aurel",
  "Autec Power Systems",
  "AVAGO TECHNOLOGIES INC",
  "AVANTEK INC",
  "Aven",
  "Avery Dennison",
  "AWINIC(Shanghai Awinic Tech)",
  "Axelite Tech",
  "Axiomtek",
  "AZ Displays",
  "Azoteq",
];
export const alphabetB = [
  "B B Battery",

  "B&F Fastener Supply",
  "B&K Precision",
  "B+B SmartWorx (Advantech)",
  "Band Solutions, LLC",
  "BANEASA S A",
  "Banner Engineering",
  "Bantam Tools",
  "baocheng(Shandong Baocheng Elec)",
  "Barker Microfarads",
  "BASiC Semiconductor",
  "BAT WIRELESS",
  "BAY LINEAR INC",
  "BBJ",
  "BC",
  "BC(Bao Cheng Elec)",
  "BCD SEMICONDUCTOR MANUFACTURING LTD",
  "BCE-SUD",
  "BDNC (Holding) Limited",
  "BeagleBoard.org",
  "Beckman",
  "BECOM Systems GmbH",
  "BEI Duncan",
  "Beijing Hop Tech",
  "Bel Fuse, Inc.",
  "Bel Power Solutions",
  "Bel-Art Products",
  "Belden",
  "Bellnix Co., LTD.",
  "Bencent",
  "Bennic",
  "Bergquist",
  "BERYL Electronic Tech",
  "BEST",
  "Better",
  "Bettertree",
  "BHC Components",
  "BHFUSE",
  "BI Technologies",
  "Binder",
  "Binho",
  "BiPOM Electronics, Inc.",
  "Bivar, Inc.",
  "BL(Dongguan Bolin Elec)",
  "BL(Shanghai Belling)",
  "BlueCreation",
  "Bluetechnix",
  "BNS Solutions",
  "BOCA SEMICONDUCTOR CORP",
  "BOCHEN(Chengdu Guosheng Tech)",
  "Bogen",
  "BOOMELE(Boom Precision Elec)",
  "Boréas Technologies",
  "BORN",
  "Bosch Connected Devices and Solutions",
  "Bosch Sensortec",
  "Bothhand Enterprise",
  "Botron Company Inc.",
  "Bourns, Inc.",
  "Bowlicon",
  "BOYAMICRO",
  "BPS(Bright Power Semicon)",
  "Brady Corporation",
  "Brainboxes",
  "Breadware, Inc.",
  "Breve Tufvassons",
  "Bridgelux, Inc.",
  "Bridgetek",
  "BRIGHT",
  "Brightek Optoelectronics",
  "BROADCHIP",
  "Broadcom",
  "BrtLed(Bright LED Elec)",
  "Bud Industries, Inc.",
  "Bulgin",
  "Bumper Specialties, Inc.",
  "Burr Brown",
  "BYD",
  "BYTESONIC ELECTRONICS CO LTD",
];
export const alphabetC = [
  "C&D TECHNOLOGIES INC",
  "C&K",
  "Caddock Electronics, Inc.",
  "Cadeka",
  "CAIG Laboratories, Inc.",
  "Cal Test Electronics",
  "CAL-CHIP ELECTRONICS INC",
  "CALIFORNIA MICRO DEVICES CORP",
  "Canon",
  "Cantherm",
  "Capital Advanced Technologies, Inc.",
  "Capxon International Elec",
  "Carclo Technical Plastics",
  "Card Sockets",
  "Cardinal Components",
  "Carli",
  "Carling Technologies",
  "CarlisleIT",
  "Carlo Gavazzi",
  "CAVIUM NETWORKS",
  "CAX",
  "CBM America Corporation",
  "CCO(Chian Chia Elec)",
  "CCS",
  "CCTC",
  "Ceaiya",
  "CEC(Shenzhen Zhenhua Fu Elec)",
  "CEL (California Eastern Laboratories)",
  "Celduc Relais",
  "CENKER",
  "Central Semiconductor",
  "Cermetek MicroElectronics, Inc",
  "CET(Chino-Excel Tech)",
  "CETC",
  "CH Products",
  "Cha",
  "Chahua-Electric",
  "CHAMPION",
  "Changjiang Electronics Tech (CJ)",
  "Changzhou Amass Elec",
  "CHANGZHOU GALAXY CENTURY MICROELECTRONICS CO LTD",
  "Changzhou Huawei Elec",
  "Changzhou Starsea Elec",
  "Chau Light",
  "Chemtronics",
  "Chengdu Ashining Tech",
  "Chengdu Ebyte Elec Tech",
  "CHENG-YI ELECTRONIC CO LTD",
  "CHENMKO ENTERPRISE CO LTD",
  "Cherry Americas",
  "CHERRY SEMICONDUCTOR CORP",
  "Chicago Electronic Distributors",
  "Chilisin Electronics",
  "Chinamobile",
  "CHINGIS TECHNOLOGY CORP",
  "Chinocera",
  "CHINO-EXCEL TECHNOLOGY CO LTD",
  "CHINT",
  "Chip Quik, Inc.",
  "Chipanalog",
  "Chiphom",
  "Chiplus Semiconductor",
  "Chip-Rail",
  "CHIPSEA",
  "Chogori Technologies",
  "Chongqing Pingwei Tech",
  "Cicoil",
  "Cinch Connectivity Solutions",
  "Cincon",
  "Cinetech",
  "Circuit Scribe/Electroninks Writeables Inc.",
  "Cirrus Logic",
  "Cissoid",
  "Citizen Electronics Co., Ltd.",
  "Citizen Finedevice Co., LTD.",
  "Citizen Finetech Miyota",
  "City Technology",
  "Cixi Kefa Elec",
  "Cixi Tonver Elec",
  "CJ",
  "CJE",
  "cjiang(Changjiang Microelectronics Tech)",
  "CJT(Changjiang Connectors)",
  "Ckmtw(Shenzhen Cankemeng)",
  "CKS",
  "Clarostat (Honeywell Sensing and Productivity Solutions)",
  "Cliff",
  "C-MAC",
  "C-Max",
  "CML Innovative Technologies",
  "CML Microcircuits",
  "Cmsemicon",
  "CnC Tech",
  "CND-tek",
  "CNIBAO",
  "CNJM",
  "CNR",
  "COBHAM PLC",
  "Cogent Computer Systems",
  "CogniMem",
  "COILANK INTERNATIONAL",
  "Coilcraft",
  "Coilmaster Elec",
  "COILMX",
  "Coiltronics",
  "COLLMER SEMICONDUCTOR INC",
  "Comair Rotron",
  "Comchip Technology",
  "Comet America",
  "COMLINEAR CORP",
  "Compit",
  "COMSET SEMICONDUCTORS",
  "Comus International",
  "CONCRAFT",
  "Conductive Containers, Inc.",
  "ConductRF",
  "CONEC",
  "CONEXANT SYSTEMS",
  "CONEXCON GROUP",
  "congatec",
  "Connect One",
  "ConnectBlue",
  "CONNFLY Elec",
  "Connor-Winfield",
  "CONQUER",
  "Construction Resource Management, LLC",
  "Conta-Clip",
  "Contelec",
  "CONTINENTAL DEVICE INDIA LTD",
  "Control Resources",
  "Convert Semiconductor",
  "Cooper Bussmann",
  "Cooper Industries",
  "Copeland Communications Inc.",
  "Corebai Microelectronics",
  "COREX",
  "Cornell Dubilier Electronics",
  "Cortina Systems",
  "Cosel",
  "COSEMITECH",
  "COSINE",
  "Cosmo Electronics",
  "Coto Technology",
  "COV",
  "CR Magnetics, Inc.",
  "Cramer",
  "CRC",
  "CREATEK",
  "Cree",
  "Crescent",
  "CRIMSON SEMICONDUCTOR INC",
  "Critical Link",
  "CRMICRO",
  "Cross chip",
  "Crouzet",
  "Crowd Supply, Inc.",
  "Crydom Inc",
  "Crystal Clear Technology Sdn. Bhd.",
  "CRYSTAL SEMICONDUCTOR CORP",
  "Crystek Corporation",
  "CT Micro International",
  "CTI Electronics",
  "C-Ton Industries",
  "CTS Corporation",
  "CUI Devices",
  "CUI Inc.",
  "Curtis Industries",
  "Custom Computer Services",
  "Cvilux",
  "CW Industries",
  "CX(Dongguan Chengxing Elec)",
  "CY(Changzhou Chaoyin Elec)",
  "Cybermax",
  "CYBERSEN",
  "Cymbet",

  "Cynergy3",
  "Cyntec / Delta Electronics",
  "Cypress Semiconductor",
  "CYSTECH",
];
export const alphabetD = [
  "DIOTEC",
  "D6 Labs",
  "Daburn",
  "DACO SEMICONDUCTOR CO LTD",
  "Dagnall",
  "Daily Silver Imp Microelectronics",
  "Dailywell",
  "DAIN Elec",
  "Dallas Semiconductor",
  "Danisense",
  "Danotherm Electric",
  "Darfon Elec",
  "Dataman",
  "Dataram",
  "Datawave Wireless",
  "Datel",
  "DAVE Embedded Systems",
  "Davies Molding, LLC.",
  "DB Unlimited",
  "DC(DongChen)",
  "Decawave",
  "DEFENSE LOGISTICS AGENCY",
  "DEFENSE SUPPLY CENTER COLUMBUS",
  "DEFOND",
  "DEGSON",
  "DeLorme",
  "Delta Electronics",
  "Delta Groups",
  "Del-Tron Precision",
  "Densitron",
  "Dersonic",
  "Desco",
  "DEUTSCH CORP",
  "Deutsch Group",
  "DFRobot",
  "Dialight",
  "Dialog Semiconductor",
  "DIBO",
  "Dielectric Laboratories (Knowles)",
  "Digi",
  "Digi International",
  "Digilent, Inc.",
  "Digi-Pas Technologies",
  "Digital View Group",
  "DIGITRON SEMICONDUCTORS",
  "Dinkle",
  "Diodes Incorporated",
  "DIOO",
  "Diotec Semiconductor AG",
  "Diptronics",
  "Directed Energy Inc.",
  "Discera",
  "Display Visions",
  "Displaytech",
  "DiTom Microwave Inc.",
  "DIYI Elec Tech",
  "DLK",
  "DLP Design, Inc.",
  "Dongguan Guangzhu Industrial",
  "Dongguan Salipt",
  "dosinconn",
  "DOWO",
  "DreamLNK",
  "Dremel",
  "dresden elektronik",
  "Dubilier",
  "Duratool",
  "Dutton-Lainson",
  "Dynastream Innovations",
];
export const alphabetE = [
  "E Ink",
  "EAO",
  "EasyBraid",
  "EasyDetek",
  "Eaton",
  "Eaton-Bussmann Electrical Division",
  "Eaton-Electronics Division",
  "EBM-Papst",
  "ebm-papst Inc.",
  "ECEC(ZheJiang E ast Crystal Elec)",
  "Echelon by Adesto",
  "Ecliptek",
  "eConais",
  "ECS Inc. International",
  "ECT",
  "EDAC Inc.",
  "EDL Lighting",
  "Edwards Signaling",
  "Efinix, Inc.",
  "EG Micro",
  "EIC Semiconductor",
  "EKINGLUX",
  "ELANTEC",
  "Electric Imp",
  "Electrocube",
  "Electroswitch",
  "Elenco",
  "ELITE ENTERPRISES H K CO LTD",
  "ELITE SEMICONDUCTOR MEMORY TECHNOLOGY INC",
  "Ellsworth Adhesives",
  "ELM TECHNOLOGY CORP",
  "Elmos",
  "Elna America",
  "ELPIDA MEMORY INC",
  "Elprotronic Inc.",
  "EMAC, Inc.",
  "Embedded Artists",
  "Embedded Planet",
  "EMC",
  "EMTEK",
  "Encoder Products Company",
  "Endicott Research Group",
  "ENDRIVE",
  "Energizer Battery Company",
  "EnerSys",
  "Enfis",
  "ENM Counting Instruments",
  "enmo Technologies",
  "EnOcean",
  "Enpirion",
  "EOS Power",
  "EOZ S.A.S",
  "EPC",
  "Epcos",
  "EPCOS (TDK)",
  "Epson",
  "EPtronics, Inc.",
  "Equinox Technologies",
  "Ericsson",
  "ERNI Electronics",
  "ERP Power",
  "ESMT(Elite Semicon Memory Tech)",
  "Espressif Systems",
  "ESPROS Photonics AG",
  "Essentra Access Solutions",
  "Essentra Components",
  "ESTERLINE TECHNOLOGIES CORP",
  "E-Switch",
  "E-T-A",
  "ETA-USA",
  "Ethertronics",
  "ETI Systems",
  "Etron Technology",
  "Euroquartz",
  "Eurotherm",
  "Eutech Microelectronics",
  "Ever Ohms Tech",
  "Everanalog IC design",
  "Everest-semi(Everest Semiconductor)",
  "Everlight Electronics",
  "Everspin Technologies, Inc.",
  "Exar Corporation",
  "EXCEL (SUZHOU) SEMICONDUCTOR CO LTD",
  "Excelitas Technologies",
  "Excelsys Technologies",
  "EYANG(Shenzhen Eyang Tech Development)",
  "E-Z-Hook",
];
export const alphabetF = [
  " Fairchild (ON Semiconductor)",
  "Fair-Rite Products Corp.",
  "Falconer Electronics, Inc.",
  "Fanstel Corp.",
  "Fastron Technology",
  "FCI Electronics",
  "FDK America",
  "Fedco Batteries",
  "Feeling Tech",
  "FEIG ELECTRONIC",
  "FeiHong",
  "Fengming",
  "FerriShield",
  "Ferroperm",
  "FERROXCUBE",
  "FH-BK(Guangdong Fenghua Bangke Elec)",
  "FIBOX Enclosures",
  "Finder Relays, Inc.",
  "Fingerprint Cards AB",
  "Finisar Corporation",
  "FinishAdapt",
  "FIRST COMPONENTS INTERNATIONAL",
  "First Semicon",
  "Firstohm(First Resistor & Condenser)",
  "Fischer Elektronik",
  "Fitipower Integrated Tech",
  "Flambeau, Inc.",
  "FLEx Lighting",
  "FLEX LTD",
  "Flex Power Modules",
  "Flexipanel",
  "FLIR",
  "FLIR Extech",
  "FLIR Lepton",
  "Fluke Electronics",
  "FlyWin",
  "FMD(Fremont Micro Devices)",
  "FMS(Formosa Microsemi)",
  "FORESEE",
  "Formerica Optoelectronics Inc.",
  "FORMOSA MICROSEMI CO LTD",
  "FORT",
  "Fortior Tech",
  "FORTUNE SEMICONDUCTOR CORP",
  "FORWARD INTERNATIONAL ELECTRONICS LTD",
  "Foshan Blue Rocket Elec",
  "Foshan NationStar Optoelectronics",
  "Foshan Synwit Tech",
  "Fox Electronics",
  "Foxconn",
  "Foxconn OE Technologies",
  "Fractus Antennas S.L.",
  "Fraenkische USA, LP",
  "Free2move AB",
  "Freescale Semiconductor, Inc. (NXP Semiconductors)",
  "FreeWave Technologies, Inc.",
  "Fremont Micro Devices",
  "FRONTIER ELECTRONICS CORP",
  "FSHY",
  "FSP Group",
  "FTCap",
  "FTDI",
  "FTR",
  "FUDAN MICRO",
  "FUET",
  "FUJI ELECTRIC CO LTD",
  "Fujitsu Electronics America, Inc.",
  "FUJITSU LTD",
  "FUJITSU SEMICONDUCTOR AMERICA INC",
  "Futaba Elec",
  "Future Designs, Inc.",
  "Future Technology Devices International, Ltd.",
  "FUXINSEMI",
  "Fuzetec Tech",
];
export const alphabetG = [
  "Gainsil",
  "GainSpan",
  "Galaxy",
  "GALAXY SEMI-CONDUCTOR CO LTD",
  "GANGYUAN",
  "Gantong",
  "GardTec",
  "Garmin Canada Inc.",
  "Gas Sensing Solutions Ltd",
  "Gast",
  "GATEMODE",
  "GBG",
  "GC Electronics",
  "Gcore",
  "GCT",
  "GD",
  "GDHY",
  "GE INDUSTRIAL SOLUTIONS",
  "GEC PLESSEY SEMICONDUCTORS",
  "GEDORE Tools, Inc.",
  "GEMS Sensors",
  "General Cable",
  "General Electric",
  "GENERAL INSTRUMENT CORP",
  "GENERAL SEMICONDUCTOR INC",
  "GeneSiC Semiconductor",
  "Genesys Logic",
  "Gennum",
  "Genteq",
  "GEYER ELECTRONIC e.K.",
  "GHI Electronics, LLC",
  "Giantec",
  "GigaDevice",
  "GLE",
  "Glenair",
  "GLOBAL MIXED-MODE TECHNOLOGY INC",
  "Global Power",
  "Global Specialties",
  "GlobTek, Inc.",
  "GMA",
  "GMT(Global Mixed-mode Tech)",
  "GMW ASSOCIATES",
  "GN Semic",
  "GoChip Elec Tech (Shanghai)",
  "GOFORD",
  "GOLDSTAR ELECTRON CO LTD",
  "GOLLEDGE ELECTRONICS LTD",
  "GOOD-ARK ELECTRONICS CO LTD",
  "Good-Ark Semiconductor",
  "GOODSKY",
  "GOODWORK SEMICONDUCTOR CO LTD",
  "GOOGLL(Zhaoqing Guoju Elec)",
  "Gotop",
  "Gotrend Tech",
  "Gowanda Electronics",
  "GOWIN",
  "GP(GreenPower)",
  "GPT",
  "GradConn",
  "Grayhill, Inc.",
  "GRE Alpha Electronics, Ltd",
  "Greenlee Communications",
  "Greenliant",
  "Grenergy",
  "GroupGets",
  "GSTEK(Green Solution Technology)",
  "G-Switch",
  "GTL-POWER",
  "Guangdong Hottech",
  "Guangdong TOPAZ Elec Tech",
  "Guangzhou Dtech Elec Tech",
  "Guangzhou Huanghua Elec",
  "Guangzhou Jingyou Electronic Tech",
  "GULF SEMICONDUCTOR LTD",
  "Guo Man",
  "GW",
  "GXCAS",
  "GZSJ",
];

export const alphabetH = [
  "H&D Wireless AB",

  "Hakko",
  "HALO",
  "Hammond Manufacturing",
  "Hanbo Electronic",
  "Hangzhou Nanochap Electronics",
  "Hangzhou Ruimeng Tech",
  "Hangzhou SDIC Microelectronics",
  "Hangzhou Silan Microelectronics",
  "HANGZHOU SILAN MICROELECTRONICS CO LTD",
  "HANRUN(Zhongshan HanRun Elec)",
  "Haoyu Microelectronics",
  "Harris",
  "HARTING",
  "HARVATEK",
  "Harwin",
  "HD",
  "HD SHOULDER",
  "HDK(Hokuriku Elec Industry)",
  "HDP Power",
  "HDSC",
  "HEADCON",
  "HEAO",
  "Heatron",
  "HEERMICR",
  "HELE(Harmony Elec)",
  "Helicomm",
  "Heling",
  "Helium",
  "Helix Semiconductors",
  "HellermannTyton",
  "HENIPER",
  "Henkel/LOCTITE",
  "HenLv",
  "Henrich Electronics Corporation",
  "Heraeus Nexensos USA",
  "HEWLETT PACKARD CO",
  "HEXIN",
  "HF(Xiamen Hongfa Electroacoustic)",
  "HGC(Huaguan Semicon)",
  "HGSEMI",
  "HI REL CONNECTORS INC",
  "HIECUBE",
  "High Diode",
  "HI-LINK",
  "Hillcrest Labs",
  "HI-REL COMPONENTS",
  "Hirose",
  "Hirschmann",
  "HITACHI",
  "Hitano",
  "HiTrend Tech (Shanghai)",
  "Hittite (Analog Devices)",
  "HIWA",
  "HK",
  "Hk-hotline",
  "HKR(Hong Kong Resistors)",
  "HL(Haolin Elec)",
  "HMS Networks",
  "HOAUC",
  "Hoei America Inc.",
  "Hokuriku",
  "HOLLY",
  "Hologram",
  "Holt Integrated Circuits, Inc.",
  "Holtek",
  "HoltIntegratedCircuits",
  "Holy Stone",
  "Honeywell",
  "Honeywell Aerospace",
  "Honeywell Sensing and Productivity Solutions",
  "Hongda",
  "HONGJU",
  "HONGLITRONIC(Hongli Zhihui (HONGLITRONIC))",
  "Hongzhi Elec",
  "Honor Elec",
  "HOOYA",
  "HopeRF Micro-electronics",
  "Hosonic",
  "Hoyt Electrical Instrument",
  "HR(Joint Tech Elec)",
  "HRS(Hirose)",
  "HS(H asion Electronics)",
  "Hsin Da Precision",
  "HSMC CORP",
  "HT(Shenzhen Jinyu Semicon)",
  "HTC",
  "HTV(Ningbo Bo Yue Elec)",
  "Hua Jung Components",
  "HUAKE",
  "HUASHUO",
  "HUAWEI",
  "HUAXIN",
  "Huaxing Mechanical-Elec.",
  "HUAYI",
  "HUAYING",
  "Hubei KENTO Elec",
  "HUBER+SUHNER",
  "HUI JU",
  "Hunan Xiangyee in S&T",
  "HVDIODE",
  "HVM Technology, Inc.",
  "HX(hengjiaxing)",
  "HX(Zhejiang Yueqing Hongxing Elec)",
  "HXT",
  "HY ELECTRONIC CORP",
  "HYBRID SYSTEMS CORP",
  "HYCON Tech",
  "HYP (Hongyuan Precision)",
  "HYPERTRONICS CORP",
  "HYPWR",
];
export const alphabetI = [
  " I/O Interconnect",

  "IAR Systems Software Inc",
  "iBASE Technology",
  "IBM MICROELECTRONICS",
  "IC MICROSYSTEMS SDN BHD",
  "IC Plus",
  "ICCNexergy",
  "ICE Components",
  "iC-Haus",
  "ICMAN Tech",
  "IDCHIP",
  "Ideal-tek",
  "IDEC",
  "IEI",
  "IHHEC(HOLY STONE ENTERPRISE CO., LTD)",
  "II-VI INC",
  "IKSEMICON",
  "Illinois Capacitor",
  "Illinois Tool Works",
  "ILLUMRA",
  "ILSI America",
  "Imagecraft",
  "IMPALA LINEAR CORP",
  "INCHANGE SEMICONDUCTOR CO LTD",
  "Industrial Fiber Optics, Inc.",
  "Industrial Shields",
  "Infineon",
  "Infineon Technologies",
  "INFORMATION STORAGE DEVICES",
  "INGHAi",
  "Initial State Technologies, Inc.",
  "Injectorall",
  "INJOINIC",
  "INMOS",
  "InnoSenT GmbH",
  "Inolux",
  "INPAQ",
  "Inphi",
  "Insight SiP",
  "Insignis Technology Corporation",
  "Inspired LED",
  "Integra Technologies",
  "Integrated Circuit Systems",
  "INTEGRATED CIRCUIT TECHNOLOGY CORP",
  "Integrated Device Technology (IDT)",
  "Integrated Power Designs",
  "Integrated Silicon Solution, Inc. (ISSI)",
  "Intel",
  "Intematix",
  "Interlink Electronics",
  "International Components Corp.",
  "International Rectifier",
  "INTERNATIONAL RECTIFIER CORP",
  "International Resistive",
  "INTERPOINT CORP",
  "Intersil (Renesas Electronics America)",
  "InvenSense",
  "Inventek Systems",
  "Inventus Power",
  "Io Audio Technologies",
  "IoTize",
  "IPDiA",
  "IQD Frequency Products",
  "IRdopto",
  "IRISO Electronics",
  "IRTOUCH Systems Co., Ltd.",
  "Isabellenhuette",
  "ISAHAYA ELECTRONICS CORP",
  "ISC",
  "Isocom Components 2004 Ltd.",
  "ITE TECH INC",
  "ITT",
  "ITT Cannon",
  "ITT Interconnect Solutions",
  "IWATT",
  "iWave Systems",
  "IXYS / Littelfuse",
  "IXYS Integrated Circuits Division / Littelfuse",
  "IXYS RF / Littelfuse",
];

export const alphabetJ = [
  "JAE Electronics",

  "Jameson LLC",
  "Jamicon",
  "Japan Radio",
  "Jauch Quartz",
  "JBL Products, Inc.",
  "JCHL(Shenzhen Jing Chuang He Li Tech)",
  "JEC",
  "Jennic",
  "Jensen Global Inc.",
  "JESTEK",
  "JETEKPS",
  "JF",
  "JGHC",
  "JH",
  "JIANGSU CHANGJIANG ELECTRONICS TECHNOLOGY CO LTD",
  "Jiangsu Huaneng Elec",
  "Jiangsu JieJie Microelectronics",
  "Jiangsu RUNIC Tech",
  "Jiaxing Heroic Elec Tech",
  "Jilin Sino-Microelectronics",
  "JILN",
  "Jimson",
  "JINAN JINGHENG ELECTRONICS CO LTD",
  "Jing Extension of the Electronic Co.",
  "JINJIA",
  "Jinlai",
  "JINLANG",
  "Jinlong Machinery & Electronics, Inc.",
  "Jinrui Electronic Materials Co.",
  "Jixin",
  "JKL Components Corporation",
  "JML",
  "Johanson Dielectrics, Inc.",
  "Johanson Technology",
  "Jonard Tools",
  "JoulWatt Tech",
  "JRC",
  "JSC INTEGRAL",
  "JST",
  "JSY-KJ",
  "Judco Manufacturing, Inc.",
  "JUNSHINE",
  "JUSHUO",
  "JWT",
];
export const alphabetK = [
  " Kaga Electronics USA",
  "Kailh",
  "Kaimei Electronic CORP",
  "Kaltman Creations",
  "Kamaya Electric",
  "KDS Daishinku",
  "KE Kitagawa",
  "Keene Village Plastics",
  "KEKO Varicon d.o.o.",
  "KELIKING",
  "KEMET",
  "Kemit",
  "Kennedy Labs",
  "Kester",
  "KET",
  "KEXIN",
  "Keysight Technologies",
  "Keystone Electronics Corp.",
  "KFSON",
  "Khadas",
  "KIA Semicon Tech",
  "Kilo International",
  "KINETIC",
  "Kingbright",
  "Kingcore",
  "Kionix",
  "Kioxia America, Inc.",
  "Kissler",
  "Kitronik",
  "KIWI",
  "Klein Tools",
  "KNIPEX Tools",
  "Knitter-switch",
  "Knowles",
  "Knowles Acoustics",
  "Knowles DLI",
  "Knowles Johanson Manufacturing",
  "Knowles NOVACAP",
  "Knowles Voltronics",
  "KNSCHA",
  "KOA CORP",
  "KOA Speer Electronics, Inc.",
  "Kodenshi AUK",
  "KODENSHI AUK CORP",
  "Koher",
  "Korea Electric Terminal",
  "Korean Hroparts Elec",
  "KS",
  "KSM Electronics Inc.",

  "KSS(KAI SUH SUH ENTERPRISE)",
  "KST(K.S Terminals)",
  "Kübler, Inc.",
  "KUKA Robotics",
  "KUM",
  "KUNBUS GmbH",
  "Kycon",
  "KYET",
  "KYOCERA Corporation",
  "Kyocera Display",
  "KYX",
];
export const alphabetL = [
  "L3 Narda-MITEQ",
  "LabJack",
  "Laird",
  "Laird - Antennas",
  "Laird - EMI",
  "Laird - Signal Integrity Products",
  "Laird Connectivity",
  "Laird Thermal Materials",
  "Laird Thermal Systems",
  "Lantiq",
  "Lantronix",
  "LAPIS SEMICONDUCTOR CO LTD",
  "Lapp",
  "Lapp Group",
  "Lascar Electronics",
  "Laser Technology Inc.",
  "Lattice Semiconductor",
  "LCSC",
  "LCX(Shenzhen LCHSTAR Elec)",
  "LEADCHIP",
  "Leader Tech Inc.",
  "Leadtrend Tech",
  "LEANSTAR",
  "LECI",
  "LED Engin",
  "LEDdynamics, Inc.",
  "Ledex Dormeyer Saia",
  "LEDiL",
  "Legion",
  "Legrand",
  "Leiditech",
  "Lelon Electronics",
  "LEM USA, Inc.",
  "LEMO",
  "Leopard Imaging Inc.",
  "LEVEL ONE",
  "LG Innotek",
  "LGE",
  "Lightech",
  "Lighting Science Group",
  "LIGHTNING",
  "Lime Microsystems",
  "LIN Engineering",
  "Linear Technology / Analog Devices",
  "LINFINITY MICROELECTRONICS",
  "Link Labs",
  "LINKSEMI",
  "Linx Technologies",
  "Liown",
  "lipoo",
  "LITEON",
  "Lite-On, Inc.",
  "Littelfuse",
  "LIZ Elec",
  "LM Technologies",
  "LMB Heeger, Inc.",
  "Loadstar Sensors",
  "Logic PD, Inc.",
  "Logical Systems",
  "Longkingdom",
  "LONTEN",
  "LORAS INDUSTRIES INC",
  "Lorlin",
  "LOTES",
  "LOWPOWER",
  "LR",
  "LRC",
  "LSD",
  "LSR",
  "LulzBot",
  "Lumberg Automation",
  "Lumex, Inc.",
  "Lumileds",
  "Luminus Devices",
  "Lumissil Microsystems",
  "Luna Optoelectronics",
  "Luxo",
  "LUXTECH",
  "LX",
  "LY",
];
export const alphabetM = [
  "M3TEK",
  "M5Stack",
  "Macchina",
  "MACHINE INTELLIGENCE",
  "MACOM Technology Solutions",
  "Macraigor Systems",
  "Macronix",
  "Made in China",
  "Maestro Wireless Solutions (Lantronix)",
  "MAGLAYERS",
  "Mag-LED",
  "Magn Tek",
  "MagnaChip",
  "Magna-Power Electronics",
  "Magnasphere Corp.",
  "Magnecraft",
  "Magsonder",
  "Makeblock",
  "Mallory Sonalert Products",
  "Man Yue Tech",
  "Maple Systems",
  "Maplesemi",
  "Marktech Optoelectronics",
  "Marlow Industries, Inc.",
  "Marutsuelec",
  "Marvell Semiconductor, Inc.",
  "Masach",
  "Master Appliance Corp.",
  "MATRA DESIGN SEMICONDUCTOR",
  "MATRIX Industries",
  "Matrix Orbital",
  "Matsuo",
  "MaxBotix Inc.",
  "MAXIC Tech",
  "Maxim Integrated",
  "MaxLinear",
  "Maxscend",
  "MaxStream (Digi International)",
  "Maxwell Technologies, Inc.",
  "Mazet",
  "MAZO",
  "MBI",
  "MCM Electronics",
  "MDD(Microdiode Electronics)",
  "MDE SEMICONDUCTOR INC",
  "MEAN WELL",
  "Measurement Specialties",
  "Meatrol",
  "MEC switches",
  "MECHANIC",
  "Mechatronics",
  "Mechatronics Bearing Group",
  "Meder",
  "MegaChips",
  "Megawin Tech",
  "MEIHUA",
  "Meled",
  "Melexis",
  "Memory Protection Devices",
  "MEMSIC",
  "Menda/EasyBraid",
  "MENTOR GMBH & CO PRAZISIONS BAUTEILE KG",
  "Mercury United",
  "MERITEK ELECTRONICS CORP",
  "Mersen",
  "Meshnetics",
  "Me-TECH",
  "Metrodyne Microsystem",
  "METZ CONNECT",
  "MG Chemicals",
  "Micrel",
  "Micrium",
  "Micro Commercial Components (MCC)",
];

export const alphabetN = [
  "NA",

  "N2Power",
  "Nakagawa",
  "NAMAE",
  "Nanjing AH Elec S & T",
  "Nanjing Ouzhuo Tech",
  "Nanjing Shiheng Elec",
  "NanJing ZhongXu Elec",
  "Nanmac",
  "Nantong Jianghai Capacitor",
  "National Control Devices",
  "National Semiconductor",
  "NATLINEAR",
  "Navitas Semiconductor",
  "NBC",
  "NDK",
  "Nearson",
  "NEC",
  "NEC COMPOUND SEMICONDUCTOR DEVICES LTD",
  "Neonode",
  "NEOTEC",
  "Nesscap Co., Ltd",
  "NetBurner, Inc.",
  "Neutrik",
  "New Japan Radio (NJR)",
  "NEvW JERSEY SEMICONDUCTOR PRODUCTS INC",
  ",vNewava",
  "Newhaven Display, Intl.",
  "Nexperia",
  "Next Industries SRL, The Tactigon",
  "nextron(Nextronics Engineering)",
  "NF(Ningbo Forward Relay Corp)",
  "NHLC",
  "NI-BOXING",
  "NIC Components",
  "NICHIA CORP",
  "Nichicon",
  "Nidec Copal Electronics",
  "NIHON INTER ELECTRONICS CORP",
  "NIKO Semicon",
  "NimbeLink",
  "Ningbo Kangnex Elec",
  "Ningbo Keke New Era Appliance",
  "Ningbo Songle Relay",
  "Ningbo Xinlaiya Elec.",
  "NIPPON PRECISION CIRCUITS INC",
  "Nippon Tanshi",
  "Nissei",
  "Nistronics",
  "NKK Switches",
  "NMB Technologies Corp.",
  "NorComp",
  "Nordic Semiconductor",
  "Noritake Co., Inc.",
  "NORTH AMERICAN PHILIPS DISCRETE PRODUCTS DIV",
  "Novacap",
  "Novasom Industries",
  "Novotechnik",
  "NTE Electronics, Inc.",
  "NUMONYX",
  "Nuvoton Tech",
  "Nuvoton Technology Corporation America",
  "NVE Corporation",
];
export const alphabetO = [
  "O.C. White Co.",
  "OASIS",
  "OB(On-Bright Elec)",
  "OCIC",
  "Octavo Systems",
  "ODU",
  "Ogam Tech",
  "Ohmite",
  "Okaya",
  "OKI Semiconductor",
  "Olimex",
  "OMC",
  "Omnetics",
  "OmniVision Technologies",
  "Omron",
  "Omron Automation & Safety Services",
  "Omron Electronics Components",
  "ON Semiconductor",
  "ON Shore Technology",
  "Onion Corporation",
  "Onset Computer Corp",
  "On-Shore Technology, Inc.",
  "OptConnect",
  "OptiFuse",
  "Option NV",
  "Opto 22",
  "Opto Diode Corporation",
  "OptoSupply",
  "Opulent Americas",
  "Orient",
  "ORIENTAL SEMI",
  "Orion Fans",
  "OSEPP Electronics",
  "OSRAM Opto Semiconductors, Inc.",
  "OWON Technology Lilliput Electronics",
  "Oxley",
];

export const alphabetP = [
    "PUYA"
,
"Paccom"
,
"Packet Digital"
,
"PADAUK Tech"
,
"Panasonic"
,
"PanaVise"
,
"Pancon"
,
"Panduit Corporation"
,
'PARALIGHT'
,
"Parallax, Inc."
,
"Parker Chomerics"
,
"Parlex Corp"
,
"Particle"
,
"Partron"
,
"Patco Electronics"
,
"Patco Services"
,
"Peak Electronic Design Ltd"
,
"Peerless by Tymphany"
,
"Peng Cheng Hardware Plastic Products"
,
"Pepperl+Fuchs"
,
"Peregrine Semiconductor Corp"
,
"Performance Semiconductor"
,
"Pericom Semiconductor Corp. (Diodes Incorporated)"
,
"Pervasive Displays"
,
"PFC Device"
,
"PFLITSCH"
,
"phaetonsemi"
,
"PHASELINK CORP"
,
"PHIHONG USA"
,
"PHILIPS COMPONENTS"
,
"Philips Semicons"
,
"Phoenix America"
,
"Phoenix Contact"
,
"Phoenix Mecano"
,
"Phoenix Passive Components"
,
"Phyton, Inc."
,
"Pi Supply"
,
"PIC GmbH"
,
"Pico Technology"
,
"Piher Sensing Systems, an Amphenol company"
,
"PILZ"
,
"Pimoroni"
,
"PINREX"
,
"PIP"
,
"pi-top"
,
"PLESSEY SEMICONDUCTORS"
,
"Pletronics"
,
"PLX"
,
"PMC-SIERRA INC"
,
"PN SILICON"
,
"Pokit Innovations"
,
"Pololu Corporation"
,
"Pomona Electronics"
,
"Pontiac Coil, Inc."
,
"Portescap"
,
"Potens"
,
"Power Amp Design"
,
"POWER INNOVATIONS LTD"
,
"Power Integrations"
,
"Powercast"
,
"Powerex, Inc."
,
"PowerFilm Inc."
,
"POWERSOLVE ELECTRONICS LTD"
,
"PowTech(CR-PowTech(Shanghai))"
,
"PRD Plastics"
,
"Preci-Dip"
,
"Precision Brand"
,
"Precision Design Associates, Inc."
,
"Precision Electronics"
,
"Precision Electronics Corporation"
,
"PRECISION MONOLITHICS INC"
,
"Precision Technology, Inc."
,
",Premier Magnetics"
,
"PRO-AN ELECTRONIC CO LTD"
,
"ProAnt"
,
"PROD Tech"
,
"Prokit's Industries"
,
"PROMAX-JOHNTON CORP"
,
"PROTEK DEVICES"
,
"Protektive Pak"
,
"PSA(Prosperity Dielectrics)"
,
"pSemi"
,
"PTC(Princeton Tech)"
,
"PTR HARTMANN GmbH"
,
"PTTC(Polytronics Tech)"
,
"PUI Audio, Inc."
,
"PULS"
,
"Pulsar"
,
"Pulse Electronics"
,
"PULSECORE SEMICONDUCTOR"
,
"PulseR"
,
"PUOLOP"
,
"Pycom"
]
export const alphabetQ = [
  "QAMcn",
  "QIACHIP",
  "Qimonda",
  "Qingdao Eastsoft Communication Tech",
  "Qingxian Zeming Langxi Elec",
  "Qoitech",
  "Qorvo",
  "QP Semiconductor",
  "QT Brightek",
  "QT OPTOELECTRONICS",
  "Quadcept",
  "Qualcomm",
  "QUALITY SEMICONDUCTOR INC",
  "Qualtek Electronics Corp.",
  "Quam",
  "Quam Nichols",
  "Quarton, Inc.",
  "Quatech",
  "Quectel",
  "Quest Manufacturing",
  "Quest Technology International",
  "QUICK",
  "Quick Logic",
  "Quickfilter Technologies LLC",
  "QX Micro Devices",
];
export const alphabetR = [
"Rabbit Semiconductor (Digi)"
,
"Radial Magnet, Inc."
,
"Radiall USA, Inc."
,
"Radio Bridge Inc."
,
"Radiocrafts"
,
"Radiometrix"
,
"Radios"
,
"Radiotronix"
,
"RAF"
,
"RAFI"
,
"Rainsun microwave Tech"
,
"RALEC"
,
"Raltron"
,
"Ramtron (Cypress Semiconductor)"
,
"Raspberry Pi"
,
"RAYTHEON SEMICONDUCTOR"
,
"RayVio"
,
"RCA SOLID STATE"
,
"RCD"
,
"RCH"
,
"Reactor-Micro"
,
"RECOM Power"
,
"Rectron"
,
"Red Lion"
,
"Redpine Signals"
,
"Remington Industries"
,
"Renco"
,
"RENERGY"
,
"Renesas Electronics America"
,
"Resistor.Today"
,
"ReVibe Energy"
,
"RevX Systems"
,
"RF Micro Devices Inc"
,
"RF Monolithics"
,
"RF Solutions"
,
"RF360 EUROPE GMBH"
,
"RFbeam Microwave GmbH"
,
"RFE INTERNATIONAL INC"
,
"RFIC"
,
"RFMD"
,
"RFsister"
,
"RGB-Tech"
,
"RI SHENG"
,
"Richtek"
,
"RICOH Electronic Devices Co., LTD."
,
"Riedon"
,
"Rieker Inc"
,
"Rigado"
,
"RIGOL Technologies"
,
"Rittal"
,
"River Eletec"
,
"RK Rose+Krieger GmbH"
,
"RUGAO DACHANG ELECTRONIC CO LTD"
,
"RUILON(Shenzhen Ruilongyuan Elec)"
,
"RushUp"
,
"Rust-Oleum"
,
"RYCHIP Semiconductor Inc."
]
export const alphabetS = [
  "S&S",
  "Sagrad",
  "Sam&wing",
  "SAMHOP MICROELECTRONICS CORP",
  "Samhwa",
  "Samsung Electro-Mechanics",
  "Samsung Semiconductor",
  "Samtec, Inc.",
  "Samwha USA",
  "Samwin",
  "SamYoung Electronics",
  "SanDisk",
  "Sanken Electric Co., Ltd.",
  "SANTE",
  "SANYEAR",
  "Sanyo Denki",
  "Sanyo Semiconductor",
  "Saronix",
  "SART(Nanjing Sart Tech)",
  "Sata Tools(ShangHai)",
  "Schaffner EMC, Inc.",
  "SchmartBoard",
  "Schneider",
  "Schott",
  "SCHUNK",
  "Schurter",
  "SCS",
  "SCT",
  "Seagate",
  "Seaward Elec",
  "SECOS CORP",
  "Seeed",
  "Seek Thermal",
  "Segger Microcontroller Systems",
  "SEI(Stackpole Elec)",
  "Seiko Instruments, Inc.",
  "Semelab",
  "Semflex",
  "SEMICONDUCTOR TECHNOLOGY INC",
  "SEMICONDUCTORS INC",
  "Semikron",
  "Semiment",
  "SemiQ",
  "Semitec",
  "SEMIWARE",
  "Semtech",
  "Senba Sensing Tech",
  "Senix",
  "Sensata Technologies",
  "Sensata Technologies – Airpax",
  "Sensata Technologies – BEI Sensors",
  "Sensata Technologies – Crydom",
  "Sensata Technologies – Deltatech",
  "Sensata Technologies – Kavlico Pressure Sensors",
  "Senseair",
  "Sensirion",
  "SMC Corporation of America",
  "SMC Diode Solutions",
  "SMITHS GROUP PLC",
  "Smiths Interconnect",
  "SMK Corp.",
  "S-MOS SYSTEMS",
  "Soberton, Inc.",
  "SOC(Shenzhen SinOne Microelectronics)",
  "SOCAY Elec",
  "SOFNG",
  "Softec",
  "Sola/Hevi-Duty",
  "SolaHD",
  "SOLA-IC",
  "SolidRun",
  "Solomon Systech",
  ",Song Chuan",
  "SONIX",
  "Soshin",
  "SOURIAU-SUNBANK Connection Technologies",
  "Southchip Semicon",
  "SPANSION INC",
  "SparkFun",
  "SPC",
  "Spec Sensors",
  "Speco",
  "Spectra Symbol",
  "Spectrah Dynamics",
  "SPECTRALINEAR INC",
  "Spectrol",
  "Spectrum Control",
  "Spectrum Digital",
  "SpotSee",
  "SPRAGUE ELECTRIC CO",
  "Sprague Goodman",
  "SPS",
  "SPTECH",
  "Square D",
  "SRA Soldering Products",
  "SRD(Shenzhen Sincerity Tech)",
  "SSI Technologies, Inc.",
  "SST Sensing",
  "SST(Microchip Tech)",
  "Stackpole Electronics, Inc.",
  "Staco Energy Products Co.",
  "Stancor",
  "Standex Electronics",
  "STANDEXMEDER",
  "Stanley Electric",
  "Starpower",
  "STARTECH SEMICONDUCTOR INC",
  "State of the Art",
  "STC Micro",
  "STE(Songtian Elec)",
  "Steinel",
  "STEIPU",
  "Stellar Labs",
  "Stens",
  "ST-Ericsson",
  "Steute",
  "Steward",
  "Stewart Connector",
  "STMicroelectronics",
  "Storm Interface",
  "STWXE",
  "Sullins Connector Solutions",
  "Sumida Corporation",
  "SUMITOMO",
  "SUN Electronic Industries",
  "SUNCON(SUN Elec Industries)",
  "SUNGMUN",
  "SunLED",
  "SUNLIGHT",
  "Sunlord",
  "Sunltech Tech",
  "SUNMATE Elec",
  "Sunon",
  "SUNX",
  "SUP",
  "SUPER",
  "Super micro Computer, Inc",
  "Superior Electric",
  "Supertex",
  "SURFACE MOUNTABLE ELECTRONIC COMPONENTS INC",
  "Surge Components",
  "SURGING",
  "Su'scon",
  "Susumu",
  "Suzhou Good-Ark Elec",
  "Suzhou Liming Elec",
  "SVTronics Inc.",
  "Swanstrom Tools",
  "Swissbit",
  "Switch Components",
  "Switchcraft / Conxall",
  "SXN(Shun Xiang Nuo Elec)",
  "Syfer",
  "Synapse Wireless",
  "SYNAPTICS INC",
  "SYNC POWER CORP",
  "Syndesy Technologies, Inc.",
  "SYNERGY SEMICONDUCTOR CORP",
  "SYNSEMI INC",
  "SYSTEM GENERAL CORP",
  "System-On-Chip Technologies",
];
export const alphabetU = [
  "Ubibot",
  "u-blox",
  "UDE Corp",
  "UDOO",
  "UG(Univision Semicon)",
  "Ultra Librarian",
  "UMAX",
  "UMW(Youtai Semiconductor Co., Ltd.)",
  "UNICORN MICROELECTRONICS CORP",
  "Unictron",
  "U-NIK",
  "Union Semiconductor",
  "UNI-ROYAL(Uniroyal Elec)",
  "UNI-SEMI",
  "UNISONIC TECHNOLOGIES CO LTD",
  "United Chemi-Con",
  "United Monolithic",
  "UnitedSiC",
  "Uni-Trend Tech",
  "UNITRODE CORP",
  "Universal Lighting Technologies",
  "uPI Semiconductor",
  "US Relays and Technology, Inc.",
  "US Sensor",
  "USAKRO",
  "US-Lasers, Inc.",
  "USound GmbH",
  "USR IOT",
  "UTC(Unisonic Tech)",
];
export const alphabetV = [
  "Venkel",
  "Verivolt",
  "VersaLogic Corporation",
  "VersaSense",
  "Vesper",
  "VIA Tech",
  "Vicor",
  "Vicotee",
  "VICTOR(Double King Industrial Holdings)",
  "Viega",
  "Vigortronix",
  "VIIYONG",
  "Viking Technology",
  "V-INFINITY LLC",
  "Virtium",
  "VISATON",
  "Vishay",
  "Vishay / BCcomponents",
  "Vishay / Beyschlag",
  "Vishay / Dale",
  "Vishay / Huntington Electric, Inc.",
  "Vishay / Semiconductor - Diodes Division",
  "Vishay / Semiconductor - Opto Division",
  "Vishay / Sfernice",
  "Vishay / Siliconix",
  "Vishay / Spectrol",
  "Vishay / Sprague",
  "Vishay / Thin Film",
  "Vishay / Vitramon",
  "Vishay Precision Group",
  "Vision Engineering",
  "Visual Communications Company, LLC",
  "VITESSE SEMICONDUCTOR CORP",
  "Vitrohm",
  "Volex",
  "Vollgo",
  "Voltronics",
  "Vox Power",
  "VP",
  "VPG Foil",
  "VPG Micro-Measurements",
  "VPT COMPONENTS",
  "VT(Vertical Technology)",
];
