export const HeadingOfTables = [
  "Inventory",
  "Pricing",
  "Actions",
  "DataSheet",
  "Factory Lead Time",
  "Life Cycle Status",
  "Contact Material", 
  "Contact Plating",
  "Mount",
  "Package / Case",
  "Number of Pins",
  "Material",
  "Housing Material",
  "Shape",
  "Packaging",
  "Published",
  "Series",
  "CPC",
  "Pbfree Code",
  "Part Status",
  "Moisture Sensitivity Level (MSL)",
  "Number of Terminations",
  "Termination",
  "ECCN Code",
  "Connector Type",
  "Number of Positions",
  "Max Operating Temperature",
  "Min Operating Temperature",
  "Color",
  "Gender",
  "Voltage - Rated",
  "Additional Feature",
  "Contact Finish - Mating",
  "MIL Conformance",
  "DIN Conformance",
  "IEC Conformance",
  "Filter Feature",
  "Mixed Contacts",
  "Option",
  "Total Number of Contacts",
  "Orientation",
  "Depth",
  "Reach Compliance Code",
  "Current Rating",
  "Frequency",
  "Approval Agency",
  "Lead Pitch",
  "Number of Contacts",
  "Mating Information",
  "Contact Gender",
  "Empty Shell",
  "Operating Supply Voltage",
  "Backshell Type",
  "Body/Shell Style",
  "Interface",
  "ELV",
  "Max Supply Voltage",
  "Min Supply Voltage",
  "Coupling Type",
  "Number of Ports",
  "Accessory Type",
  "Number of Poles",
  "Sealable",
  "Density",
  "Number of Drivers",
  "Outside Diameter",
  "Number of Receivers",
  "Head Diameter",
  "Diameter",
  "Height",
  "Length",
  "Width",
  "Thickness",
  "Diameter - Inside",
  "Radiation Hardening",
  "REACH SVHC",
  "Flammability Rating",
  "Lead Free",
];
